services:
  checker:
    build:
      context: ${PROJECT_ROOT}
      dockerfile: ${LESSON_PATH}/checker/Dockerfile
    networks:
      lesson_network:
        ipv4_address: ${CHECKER_IP}
    environment:
      - TIMEOUT_DURATION=${TIMEOUT_DURATION:-30s}
      - CHECKER_PORT=${CHECKER_PORT}
      - CHECKER_IP=${CHECKER_IP}
    volumes:
      - ${PROJECT_ROOT}/${LESSON_PATH}/stdout.log:/app/stdout.log
    profiles:
      - local-checker

  lesson:
    build:
      context: ${PROJECT_ROOT}
      dockerfile: ${LESSON_PATH}/app/Dockerfile
    depends_on:
      - checker
    networks:
      - lesson_network
    environment:
      - TIMEOUT_DURATION=${TIMEOUT_DURATION:-30s}
      - CHECKER_MULTIADDR=${CHECKER_MULTIADDR}
    volumes:
      - ${PROJECT_ROOT}/${LESSON_PATH}/stdout.log:/app/stdout.log
    profiles:
      - always

networks:
  lesson_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.27.1.0/24