services:
  lesson:
    build:
      context: ./app
      dockerfile: Dockerfile
    stop_grace_period: 1m
    environment:
      - TIMEOUT_DURATION=${TIMEOUT_DURATION:-20s}
      - REMOTE_ADDR=${REMOTE_ADDR:-/ip4/172.16.16.17/tcp/9092}
    volumes:
      - ./stdout.log:/app/stdout.log
    networks:
      workshop-net:
        ipv4_address: 172.16.16.16

  checker:
    build:
      context: ./checker
      dockerfile: Dockerfile
    container_name: ucw-checker-02-tcp-transport-py
    depends_on:
      - lesson
    stop_grace_period: 1m
    environment:
      - TIMEOUT_DURATION=${TIMEOUT_DURATION:-20s}
      - REMOTE_PEERS=${REMOTE_PEERS:-/ip4/172.16.16.16/tcp/0}
    volumes:
      - ./checker.log:/app/checker.log
    networks:
      workshop-net:
        ipv4_address: 172.16.16.17

networks:
  workshop-net:
    name: workshop-net
    external: false
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.16.0/24 