services:
  lesson:
    build:
      context: ${PROJECT_ROOT}
      dockerfile: ${LESSON_PATH}/app/Dockerfile
    container_name: workshop-lesson
    stop_grace_period: 1m
    environment:
      - TIMEOUT_DURATION=${TIMEOUT_DURATION:-30s}
      - REMOTE_PEERS=${REMOTE_PEERS:-/ip4/172.16.16.17/udp/9091/quic-v1,/ip4/172.16.16.18/udp/9091/quic-v1}
      - BOOTSTRAP_PEERS=${BOOTSTRAP_PEERS:-/ip4/172.16.16.17/udp/9091/quic-v1/p2p/12D3KooWDj4uNjMpUtESkyJa2ZB6DtXg5PKC4pTUptJixE7zo9gB,/ip4/172.16.16.18/udp/9091/quic-v1/p2p/12D3KooWFg4cGhT7UAHJ6D2CzNCkr7MX6eN9vjhK1xSXweHkvd1X}
    volumes:
      - ${PROJECT_ROOT}/${LESSON_PATH}/stdout.log:/app/stdout.log
    networks:
      workshop-net:
        ipv4_address: 172.16.16.16

  checker-01:
    image: ghcr.io/libp2p/universal-connectivity-workshop/ucw-checker-en:latest
    container_name: ucw-checker-en-01
    depends_on:
      - lesson
    stop_grace_period: 1m
    environment:
      - TIMEOUT_DURATION=${TIMEOUT_DURATION:-30s}
      - LISTEN_ADDRS=${LISTEN_ADDRS:-/ip4/172.16.16.17/udp/9091/quic-v1}
      - BOOTSTRAP_PEERS=${BOOTSTRAP_PEERS:-/ip4/172.16.16.18/udp/9091/quic-v1/p2p/12D3KooWFg4cGhT7UAHJ6D2CzNCkr7MX6eN9vjhK1xSXweHkvd1X}
    volumes:
      - ${PROJECT_ROOT}/${LESSON_PATH}/checker.log:/app/checker.log
      - ${PROJECT_ROOT}/${LESSON_PATH}/12D3KooWDj4uNjMpUtESkyJa2ZB6DtXg5PKC4pTUptJixE7zo9gB.key:/app/key
    networks:
      workshop-net:
        ipv4_address: 172.16.16.17

  checker-02:
    image: ghcr.io/libp2p/universal-connectivity-workshop/ucw-checker-en:latest
    container_name: ucw-checker-en-02
    depends_on:
      - lesson
    stop_grace_period: 1m
    environment:
      - TIMEOUT_DURATION=${TIMEOUT_DURATION:-60s}
      - LISTEN_ADDRS=${LISTEN_ADDRS:-/ip4/172.16.16.18/udp/9091/quic-v1}
      - BOOTSTRAP_PEERS=${BOOTSTRAP_PEERS:-/ip4/172.16.16.17/udp/9091/quic-v1/p2p/12D3KooWDj4uNjMpUtESkyJa2ZB6DtXg5PKC4pTUptJixE7zo9gB}
    volumes:
      - ${PROJECT_ROOT}/${LESSON_PATH}/checker2.log:/app/checker.log
      - ${PROJECT_ROOT}/${LESSON_PATH}/12D3KooWFg4cGhT7UAHJ6D2CzNCkr7MX6eN9vjhK1xSXweHkvd1X.key:/app/key
    networks:
      workshop-net:
        ipv4_address: 172.16.16.18

networks:
  workshop-net:
    name: workshop-net
    external: true
