services:
  lesson:
    build:
      context: ./app
      dockerfile: Dockerfile
    stop_grace_period: 1m
    environment:
      - TIMEOUT_DURATION=${TIMEOUT_DURATION:-60}
      - INTERACTIVE=false
      - NODE_ENV=production
      - REMOTE_PEER=/ip4/172.16.16.17/tcp/9091/p2p/${CHECKER_PEER_ID:-}
    volumes:
      - .:/workspace
    networks:
      workshop-net:
    command: ["sh", "-c", "sleep 5 && node index.js > /workspace/stdout.log 2>&1"]
    depends_on:
      - checker

  checker:
    build:
      context: ./checker
      dockerfile: Dockerfile
    stop_grace_period: 1m
    environment:
      - TIMEOUT_DURATION=${TIMEOUT_DURATION:-60}
      - INTERACTIVE=false
    volumes:
      - .:/workspace
    networks:
      workshop-net:
    ports:
      - "9091:9091"  # Expose checker port for students to dial
    command: ["sh", "-c", "node index.js > /workspace/checker.log 2>&1"]

networks:
  workshop-net:
     name: workshop-net
     external: true
     driver: bridge
     ipam:
      config:
        - subnet: 172.16.16.0/25

