services:
  lesson:
    build:
      context: ./app
      dockerfile: Dockerfile
    stop_grace_period: 1m
    environment:
      - TIMEOUT_DURATION=${TIMEOUT_DURATION:-30s}
      - NODE_ENV=production
    volumes:
      - .:/workspace
    networks:
      - workshop-net
    command: ["sh", "-c", "cd /app && node index.js > /workspace/stdout.log 2>&1"]

networks:
  workshop-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.16.0/24 