services:
  lesson:
    build:
      context: ${PROJECT_ROOT}
      dockerfile: ${LESSON_PATH}/app/Dockerfile
      args:
        LESSON_PATH: ${LESSON_PATH}
    stop_grace_period: 1m
    environment:
      - TIMEOUT_DURATION=${TIMEOUT_DURATION:-20s}
      - REMOTE_PEERS=${REMOTE_PEERS:-/ip4/172.16.16.17/tcp/9092}
    volumes:
      - ${PROJECT_ROOT}/${LESSON_PATH}/stdout.log:/app/stdout.log
